package com.anaplan.engineering.azuki.irr.adapter.api

import com.anaplan.engineering.azuki.core.system.Action
import com.anaplan.engineering.azuki.core.system.ActionFactory
import com.anaplan.engineering.azuki.core.system.UnsupportedAction
import com.sun.org.slf4j.internal.LoggerFactory

interface IrrActionFactory: ActionFactory {

    fun create(cashFlowSeries: String) = unsupportedAction()
    fun addToEnd(cashFlowSeriesName: String, cashFlow: Double) = unsupportedAction()
}
private val Log = LoggerFactory.getLogger(IrrActionFactory::class.java)

private fun unsupportedAction(): Action {
    val caller = Thread.currentThread().stackTrace[3]
    Log.debug("UnsupportedAction generated by ${caller.className}.${caller.methodName}")
    return UnsupportedAction
}
